export const PROVINCE_MAP: Record<string, string> = {
  "Buenos Aires": "BuenosAires",
  "CABA": "CiudaddeBuenosAires",
  "Catamarca": "Catamarca",
  "Chaco": "Chaco",
  "Chubut": "Chubut",
  "Córdoba": "Córdoba",
  "Corrientes": "Corrientes",
  "Entre Ríos": "EntreRíos",
  "Formosa": "Formosa",
  "Jujuy": "Jujuy",
  "La Pampa": "LaPampa",
  "La Rioja": "LaRioja",
  "Mendoza": "Mendoza",
  "Misiones": "Misiones",
  "Neuquén": "Neuquén",
  "Río Negro": "RíoNegro",
  "Salta": "Salta",
  "San Juan": "SanJuan",
  "San Luis": "SanLuis",
  "Santa Cruz": "SantaCruz",
  "Santa Fe": "SantaFe",
  "Santiago Del Estero": "SantiagodelEstero",
  "Tierra Del Fuego": "TierradelFuego",
  "Tucumán": "Tucumán",
};